### ISSUE TITLE
build with gcc-6.3.0/cuda 9

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/omega_h#38]
Creating issue and copying relevant discussion from #35

From Dhyan:

Building without CUDA / kokkos and with gcc-6.3.0 gives errors like
===========================================================
/fusion/usc/opt/gcc/gcc-6.3.0/include/c++/6.3.0/bits/unique_ptr.h:158:17: note:   candidate expects 0 arguments, 1 provided
In file included from /home/nathd/omega_h/src/Omega_h_array.hpp:4:0,
                 from /home/nathd/omega_h/src/Omega_h_comm.hpp:7,
                 from /home/nathd/omega_h/src/Omega_h_array_ops.hpp:6,
                 from /home/nathd/omega_h/src/Omega_h_rcFields.cpp:4:
/home/nathd/omega_h/src/Omega_h_defines.hpp: In instantiation of ‘auto Omega_h::apply_to_omega_h_types(Omega_h_Type, const F&) [with F = Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)>]’:
/home/nathd/omega_h/src/Omega_h_rcFields.cpp:340:4:   required from here
/home/nathd/omega_h/src/Omega_h_defines.hpp:93:15: error: use of ‘Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)> [with auto:1 = int]’ before deduction of ‘auto’
       return f(I32{});
              ~^~~~~~~
/home/nathd/omega_h/src/Omega_h_defines.hpp:93:21: error: return-statement with a value, in function returning 'void' [-fpermissive]
       return f(I32{});
                     ^
/home/nathd/omega_h/src/Omega_h_defines.hpp:97:15: error: use of ‘Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)> [with auto:1 = long int]’ before deduction of ‘auto’
       return f(I64{});

=====================================================================

**Comment by jacobmerson** [comment]
@dhyan1272 I will actually install gcc@6.3.0 and try to build. That current issue that's listed is my code and it should be a quick fix.

I don't have access to cuda/9 on the SCOREC workstations so we may need to iterate on the errors there.

**Comment by jacobmerson** [comment]
@dhyan1272 I installed gcc@6.3.0 so I could test out the build and was able to fix up the issues.

There was a compiler bug that required captured class member functions to be qualified with `this->`.

Please check out the code either from my pull request #39  or [my branch](https://github.com/jacobmerson/omega_h/tree/fix-gcc-6-build).

You can turn of the warnings about `nodiscard` by setting adding the compiler flag `-Wno-attributes`.

**Comment by dhyan1272** [comment]
Build successful with CUDA 9.0 and gcc 6.3.0 !

Regards,
Dhyan
Mechanical Aerospace and Nuclear Engineering

________________________________

**Comment by jacobmerson** [comment]
Glad it worked for you. Make sure you run the test suite to verify the install.

**Comment by dhyan1272** [comment]
I will let you know after building with the new code by tomorrow.

Regards,
Dhyan
Mechanical Aerospace and Nuclear Engineering

________________________________
From: Jacob Merson ***@***.***>
Sent: Wednesday, June 8, 2022 2:06 AM
To: SCOREC/omega_h ***@***.***>
Cc: dhyan1272 ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [SCOREC/omega_h] build with gcc-6.3.0 (Issue #38)


@dhyan1272<https://github.com/dhyan1272> I installed ***@***.*** so I could test out the build and was able to fix up the issues.

There was a compiler bug that required captured class member functions to be qualified with this->.

Please check out the code either from my pull request #39<https://github.com/SCOREC/omega_h/pull/39> or my branch<https://github.com/jacobmerson/omega_h/tree/fix-gcc-6-build>.

You can turn of the warnings about nodiscard by setting adding the compiler flag -Wno-attributes.
