### PR TITLE
build with gcc/6.3.0

### LINKED ISSUE #38: build with gcc-6.3.0/cuda 9
Creating issue and copying relevant discussion from #35

From Dhyan:

Building without CUDA / kokkos and with gcc-6.3.0 gives errors like
===========================================================
/fusion/usc/opt/gcc/gcc-6.3.0/include/c++/6.3.0/bits/unique_ptr.h:158:17: note:   candidate expects 0 arguments, 1 provided
In file included from /home/nathd/omega_h/src/Omega_h_array.hpp:4:0,
                 from /home/nathd/omega_h/src/Omega_h_comm.hpp:7,
                 from /home/nathd/omega_h/src/Omega_h_array_ops.hpp:6,
                 from /home/nathd/omega_h/src/Omega_h_rcFields.cpp:4:
/home/nathd/omega_h/src/Omega_h_defines.hpp: In instantiation of ‘auto Omega_h::apply_to_omega_h_types(Omega_h_Type, const F&) [with F = Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)>]’:
/home/nathd/omega_h/src/Omega_h_rcFields.cpp:340:4:   required from here
/home/nathd/omega_h/src/Omega_h_defines.hpp:93:15: error: use of ‘Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)> [with auto:1 = int]’ before deduction of ‘auto’
       return f(I32{});
              ~^~~~~~~
/home/nathd/omega_h/src/Omega_h_defines.hpp:93:21: error: return-statement with a value, in function returning 'void' [-fpermissive]
       return f(I32{});
                     ^
/home/nathd/omega_h/src/Omega_h_defines.hpp:97:15: error: use of ‘Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)> [with auto:1 = long int]’ before deduction of ‘auto’
       return f(I64{});

=====================================================================

### PR DESCRIPTION
**Pull request by jacobmerson**
Due to a compiler defect in gcc (see
https://stackoverflow.com/questions/32097759/calling-this-member-function-from-generic-lambda-clang-vs-gcc)
the methods from the enclosing class require qualification with `this->`

This fixes #38

### CODE REVIEW

**Comment by jacobmerson** [comment]
@joshia5 please review this when you get a chance. This now build on gcc/6.3.0 I tested with kokkos and cuda on my local machine.
