### PR TITLE
Shared pointers with arrays are c++17 feature

### PR DESCRIPTION
**Pull request by jacobmerson**
Using shared pointers with arrays is a c++ 17 feature. For compatibillty with gcc/6.3.0 we need to only support pure c++14 features.

@dhyan1272

### CODE REVIEW

**Comment by jacobmerson** [comment]
@dhyan1272 This needed on other small fix as functions that contain `OMEGA_H_LAMBDA` need to be in the public scope for CUDA.

All of the tests are passing with `gcc@11.2.0` and `cuda@11.6`. Based on your email you need `gcc@6.3` and `cuda@9`. So you may hit other issues.

**Comment by jacobmerson** [comment]
@joshia5 when you get a chance can you take a look?

**Comment by joshia5** [comment]
@jacobmerson looks good. Is this commit https://github.com/SCOREC/omega_h/pull/35/commits/709f6d825cdb5145954007b091558fb88f53dd71
related to
 https://github.com/SCOREC/omega_h/issues/36 ?

**Comment by jacobmerson** [comment]
It's related in the sense that I didn't test my last pull request with CUDA and that ended up causing compilation issues. However all of the changes here are related to building with the CUDA backend so I figured it was fine to leave the commit here. I can open a separate pull request if you prefer.

**Review by joshia5 — APPROVED** [review]

**Comment by joshia5** [comment]
Looks good to me either way. Is this ready merge in now? @jacobmerson or are you waiting to hear back from dhyan if it needs other changes for the gitrm build?

**Comment by jacobmerson** [comment]
@joshia5 I think you can go ahead and merge it. I didn't hear back from dhyan either here or on the email chain we had.

**Comment by dhyan1272** [comment]
So, the build issues is gitrm was due to the gcc version we had to use (gcc 6.3.0) for compiling omega-h, (due to the limitation of cuda 9.0 being supported by gcc<=6). Had no issues in building omega-h with either gcc >=9

Regards,
Dhyan
Mechanical Aerospace and Nuclear Engineering

________________________________
From: Aditya Joshi ***@***.***>
Sent: Tuesday, June 7, 2022 3:27 PM
To: SCOREC/omega_h ***@***.***>
Cc: dhyan1272 ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [SCOREC/omega_h] Shared pointers with arrays are c++17 feature (PR #35)


Looks good to me either way. Is this ready merge in now? @jacobmerson<https://github.com/jacobmerson> or are you waiting to hear back from dhyan if it needs other changes for the gitrm build?

**Comment by jacobmerson** [comment]
@dhyan1272 you can check if this now builds with `gcc@6.3.0` (with Omega_h with CUDA) I don't think it will work with Kokkos since something in Kokkos was crashing nvcc. This commit fixes the error that you send me an email about.

**Comment by dhyan1272** [comment]
Building with CUDA without kokkos and gcc -6.3.0 gives errors like

========================================
nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
nvcc error   : 'cicc' core dumped
make[2]: *** [src/CMakeFiles/omega_h.dir/Omega_h_rcFields.cpp.o] Error 139
========================================


Building without CUDA / kokkos and with gcc-6.3.0 gives errors like
===========================================================
/fusion/usc/opt/gcc/gcc-6.3.0/include/c++/6.3.0/bits/unique_ptr.h:158:17: note:   candidate expects 0 arguments, 1 provided
In file included from /home/nathd/omega_h/src/Omega_h_array.hpp:4:0,
                 from /home/nathd/omega_h/src/Omega_h_comm.hpp:7,
                 from /home/nathd/omega_h/src/Omega_h_array_ops.hpp:6,
                 from /home/nathd/omega_h/src/Omega_h_rcFields.cpp:4:
/home/nathd/omega_h/src/Omega_h_defines.hpp: In instantiation of ‘auto Omega_h::apply_to_omega_h_types(Omega_h_Type, const F&) [with F = Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)>]’:
/home/nathd/omega_h/src/Omega_h_rcFields.cpp:340:4:   required from here
/home/nathd/omega_h/src/Omega_h_defines.hpp:93:15: error: use of ‘Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)> [with auto:1 = int]’ before deduction of ‘auto’
       return f(I32{});
              ~^~~~~~~
/home/nathd/omega_h/src/Omega_h_defines.hpp:93:21: error: return-statement with a value, in function returning 'void' [-fpermissive]
       return f(I32{});
                     ^
/home/nathd/omega_h/src/Omega_h_defines.hpp:97:15: error: use of ‘Omega_h::Mesh::get_rc_mesh_tag_from_rc_tag(Omega_h::Int, const Omega_h::TagBase*)::<lambda(auto:1)> [with auto:1 = long int]’ before deduction of ‘auto’
       return f(I64{});

=====================================================================

Regards,
Dhyan
Mechanical Aerospace and Nuclear Engineering

________________________________
From: Dhyanjyoti Nath ***@***.***>
Sent: Tuesday, June 7, 2022 4:05 PM
To: SCOREC/omega_h ***@***.***>; SCOREC/omega_h ***@***.***>
Cc: dhyan1272 ***@***.***>; Mention ***@***.***>
Subject: RE: [EXTERNAL] Re: [SCOREC/omega_h] Shared pointers with arrays are c++17 feature (PR #35)


That would be great,

Will let you know by tonight.



Regards

Dhyan



From: Jacob ***@***.***>
Sent: Tuesday, June 7, 2022 4:03 PM
To: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Subject: [EXTERNAL] Re: [SCOREC/omega_h] Shared pointers with arrays are c++17 feature (PR #35)



@dhyan1272<https://github.com/dhyan1272> you can check if this now builds with ***@***.*** (with Omega_h with CUDA) I don't think it will work with Kokkos since something in Kokkos was crashing nvcc. This commit fixes the error that you send me an email about.

**Comment by dhyan1272** [comment]
Thanks!

we had a meeting today regarding these issues.
gcc 6.3.0 / cuda 9.0 with such an old gpu card (compute capability of 3.5) may not be very suitable for performance.
So, building with CUDA on those systems is on hold now and we may look for other options.


Regards,
Dhyan
Mechanical Aerospace and Nuclear Engineering

________________________________
From: Jacob Merson ***@***.***>
Sent: Monday, June 6, 2022 3:11 PM
To: SCOREC/omega_h ***@***.***>
Cc: dhyan1272 ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [SCOREC/omega_h] Shared pointers with arrays are c++17 feature (PR #35)


Using shared pointers with arrays is a c++ 17 feature. For compatibillty with gcc/6.3.0 we need to only support pure c++14 features.

@dhyan1272<https://github.com/dhyan1272>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/SCOREC/omega_h/pull/35

Commit Summary

  *   6b72e42<https://github.com/SCOREC/omega_h/pull/35/commits/6b72e42873c0035e7e9e2f436e68c36277e20767> Shared pointers with arrays are c++17 feature

File Changes

(2 files<https://github.com/SCOREC/omega_h/pull/35/files>)

  *   M src/Omega_h_array.cpp<https://github.com/SCOREC/omega_h/pull/35/files#diff-c2459e2761c98cdfdad3c7229132b63a91b146f5aaa3c13f19338f1da2692da7> (10)
  *   M src/Omega_h_array.hpp<https://github.com/SCOREC/omega_h/pull/35/files#diff-d957db98978ea0d49aa1fca35820e7ea68bfcc3297902db6c0bde5487f2d4857> (8)

Patch Links:

  *   https://github.com/SCOREC/omega_h/pull/35.patch
  *   https://github.com/SCOREC/omega_h/pull/35.diff
